#include "platform_service.hpp"
#include "models/controller_input_descriptor.hpp"
#include "models/platform.hpp"

namespace firelight::platforms {

PlatformService::PlatformService() {
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_GAMEBOY,
      .name = "Game Boy",
      .abbreviation = "Game Boy",
      .slug = "gb",
      .fileAssociations = {"gb"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/gb",
            .inputs =
                {
                    {"A", input::GamepadInput::EastFace},
                    {"B", input::GamepadInput::SouthFace},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                }}},
      .settings = {
          CoreOption{.key = "gambatte_gbc_color_correction",
                     .defaultValue = "GBC only"},
          CoreOption{.key = "gambatte_gbc_color_correction_mode",
                     .defaultValue = "accurate"},
          CoreOption{.key = "gambatte_gbc_frontlight_position",
                     .defaultValue = "central"},
          CoreOption{.key = "gambatte_dark_filter_level", .defaultValue = "0"},
          CoreOption{.key = "gambatte_up_down_allowed",
                     .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_mix_frames", .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_gb_colorization", .defaultValue = "auto"},
          CoreOption{.key = "gambatte_gb_internal_palette",
                     .defaultValue = "GB - DMG"},
          CoreOption{.key = "gambatte_gb_bootloader",
                     .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_gb_hwmode", .defaultValue = "auto"}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_GAMEBOY_COLOR,
      .name = "Game Boy Color",
      .abbreviation = "Game Boy Color",
      .slug = "gbc",
      .fileAssociations = {"gbc"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/gbc",
            .inputs =
                {
                    {"A", input::GamepadInput::EastFace},
                    {"B", input::GamepadInput::SouthFace},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                }}},
      .settings = {
          CoreOption{.key = "gambatte_gbc_color_correction",
                     .defaultValue = "GBC only"},
          CoreOption{.key = "gambatte_gbc_color_correction_mode",
                     .defaultValue = "accurate"},
          CoreOption{.key = "gambatte_gbc_frontlight_position",
                     .defaultValue = "central"},
          CoreOption{.key = "gambatte_dark_filter_level", .defaultValue = "0"},
          CoreOption{.key = "gambatte_up_down_allowed",
                     .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_mix_frames", .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_gb_colorization", .defaultValue = "auto"},
          CoreOption{.key = "gambatte_gb_internal_palette",
                     .defaultValue = "GB - DMG"},
          CoreOption{.key = "gambatte_gb_bootloader",
                     .defaultValue = "disabled"},
          CoreOption{.key = "gambatte_gb_hwmode", .defaultValue = "auto"}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_GAMEBOY_ADVANCE,
      .name = "Game Boy Advance",
      .abbreviation = "Game Boy Advance",
      .slug = "gba",
      .fileAssociations = {"gba"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/gba",
            .inputs = {{"A", input::GamepadInput::EastFace},
                       {"B", input::GamepadInput::SouthFace},
                       {"A (turbo)", input::GamepadInput::NorthFace},
                       {"B (turbo)", input::GamepadInput::WestFace},
                       {"L", input::GamepadInput::LeftBumper},
                       {"R", input::GamepadInput::RightBumper},
                       {"L (turbo)", input::GamepadInput::LeftTrigger},
                       {"R (turbo)", input::GamepadInput::RightTrigger},
                       {"Start", input::GamepadInput::Start},
                       {"Select", input::GamepadInput::Select},
                       {"D-Pad Up", input::GamepadInput::DpadUp},
                       {"D-Pad Down", input::GamepadInput::DpadDown},
                       {"D-Pad Left", input::GamepadInput::DpadLeft},
                       {"D-Pad Right", input::GamepadInput::DpadRight},
                       {"Darken solar sensor", input::GamepadInput::L3},
                       {"Lighten solar sensor", input::GamepadInput::R3}}}},
      .settings = {
          CoreOption{.key = "mgba_solar_sensor_level", .defaultValue = "0"},
          CoreOption{.key = "mgba_gb_model", .defaultValue = "Autodetect"},
          CoreOption{.key = "mgba_sgb_borders", .defaultValue = "ON"},
          CoreOption{.key = "mgba_gb_colors_preset", .defaultValue = "0"},
          CoreOption{.key = "mgba_gb_colors", .defaultValue = "Grayscale"},
          CoreOption{.key = "mgba_use_bios", .defaultValue = "ON"},
          CoreOption{.key = "mgba_skip_bios", .defaultValue = "OFF"},
          CoreOption{.key = "mgba_frameskip", .defaultValue = "disabled"},
          CoreOption{.key = "mgba_frameskip_threshold", .defaultValue = "33"},
          CoreOption{.key = "mgba_frameskip_interval", .defaultValue = "0"},
          CoreOption{.key = "mgba_audio_low_pass_filter",
                     .defaultValue = "disabled"},
          CoreOption{.key = "mgba_audio_low_pass_range", .defaultValue = "60"},
          CoreOption{.key = "mgba_idle_optimization",
                     .defaultValue = "Remove Known"},
          CoreOption{.key = "mgba_force_gbp", .defaultValue = "OFF"},
          CoreOption{.key = "mgba_color_correction", .defaultValue = "OFF"},
          CoreOption{.key = "mgba_interframe_blending",
                     .defaultValue = "mix_smart"}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_NES,
      .name = "NES/Famicom",
      .abbreviation = "NES",
      .slug = "nes",
      .fileAssociations = {"nes"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/nes",
            .inputs =
                {
                    {"A", input::GamepadInput::EastFace},
                    {"B", input::GamepadInput::SouthFace},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                }}},
      .settings = {
          CoreOption{.key = "fceumm_apu_1", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_apu_2", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_apu_3", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_apu_4", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_apu_5", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_arkanoid_mode", .defaultValue = "mouse"},
          CoreOption{.key = "fceumm_aspect", .defaultValue = "8:7 PAR"},
          CoreOption{.key = "fceumm_game_genie", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_mouse_sensitivity", .defaultValue = "100"},
          CoreOption{.key = "fceumm_nospritelimit", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_ntsc_filter", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_overclocking", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_overscan_h_left", .defaultValue = "0"},
          CoreOption{.key = "fceumm_overscan_h_right", .defaultValue = "0"},
          CoreOption{.key = "fceumm_overscan_v_bottom", .defaultValue = "8"},
          CoreOption{.key = "fceumm_overscan_v_top", .defaultValue = "8"},
          CoreOption{.key = "fceumm_palette", .defaultValue = "default"},
          CoreOption{.key = "fceumm_ramstate", .defaultValue = "$ff"},
          CoreOption{.key = "fceumm_show_adv_sound_options",
                     .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_show_adv_system_options",
                     .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_show_crosshair", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_sndlowpass", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_sndquality", .defaultValue = "Very High"},
          CoreOption{.key = "fceumm_sndstereodelay",
                     .defaultValue = "15_ms_delay"},
          CoreOption{.key = "fceumm_sndvolume", .defaultValue = "7"},
          CoreOption{.key = "fceumm_swapduty", .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_turbo_delay", .defaultValue = "3"},
          CoreOption{.key = "fceumm_turbo_enable", .defaultValue = "None"},
          CoreOption{.key = "fceumm_up_down_allowed",
                     .defaultValue = "disabled"},
          CoreOption{.key = "fceumm_zapper_mode", .defaultValue = "clightgun"},
          CoreOption{.key = "fceumm_zapper_sensor", .defaultValue = "enabled"},
          CoreOption{.key = "fceumm_zapper_tolerance", .defaultValue = "6"},
          CoreOption{.key = "fceumm_zapper_trigger", .defaultValue = "enabled"},
      }});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_SNES,
      .name = "SNES/Super Famicom",
      .abbreviation = "SNES",
      .slug = "snes",
      .fileAssociations = {"sfc", "smc"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/snes",
            .inputs =
                {
                    {"A", input::GamepadInput::EastFace},
                    {"B", input::GamepadInput::SouthFace},
                    {"X", input::GamepadInput::NorthFace},
                    {"Y", input::GamepadInput::WestFace},
                    {"L", input::GamepadInput::LeftBumper},
                    {"R", input::GamepadInput::RightBumper},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                }}},
      .settings = {
          CoreOption{.key = "snes9x_hires_blend", .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_overclock_superfx", .defaultValue = "100%"},
          CoreOption{.key = "snes9x_up_down_allowed",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_sndchan_1", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_2", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_3", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_4", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_5", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_6", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_7", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_sndchan_8", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_layer_1", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_layer_2", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_layer_3", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_layer_4", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_layer_5", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_gfx_clip", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_gfx_transp", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_audio_interpolation",
                     .defaultValue = "gaussian"},
          CoreOption{.key = "snes9x_overclock_cycles",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_reduce_sprite_flicker",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_randomize_memory",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_overscan", .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_aspect", .defaultValue = "4:3"},
          CoreOption{.key = "snes9x_region", .defaultValue = "auto"},
          CoreOption{.key = "snes9x_lightgun_mode", .defaultValue = "Lightgun"},
          CoreOption{.key = "snes9x_superscope_reverse_buttons",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_superscope_crosshair", .defaultValue = "2"},
          CoreOption{.key = "snes9x_superscope_color", .defaultValue = "White"},
          CoreOption{.key = "snes9x_justifier1_crosshair", .defaultValue = "4"},
          CoreOption{.key = "snes9x_justifier1_color", .defaultValue = "Blue"},
          CoreOption{.key = "snes9x_justifier2_crosshair", .defaultValue = "4"},
          CoreOption{.key = "snes9x_justifier2_color", .defaultValue = "Pink"},
          CoreOption{.key = "snes9x_rifle_crosshair", .defaultValue = "2"},
          CoreOption{.key = "snes9x_rifle_color", .defaultValue = "White"},
          CoreOption{.key = "snes9x_block_invalid_vram_access",
                     .defaultValue = "enabled"},
          CoreOption{.key = "snes9x_echo_buffer_hack",
                     .defaultValue = "disabled"},
          CoreOption{.key = "snes9x_blargg", .defaultValue = "disabled"},
      }});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_N64,
      .name = "Nintendo 64",
      .abbreviation = "N64",
      .slug = "n64",
      .fileAssociations = {"n64", "z64", "v64"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/n64",
            .inputs =
                {
                    {"A", input::GamepadInput::SouthFace},
                    {"B", input::GamepadInput::WestFace},
                    {"Z", input::GamepadInput::LeftTrigger},
                    {"L", input::GamepadInput::LeftBumper},
                    {"R", input::GamepadInput::RightBumper},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"C-Up", input::GamepadInput::RightStickUp},
                    {"C-Down", input::GamepadInput::RightStickDown},
                    {"C-Left", input::GamepadInput::RightStickLeft},
                    {"C-Right", input::GamepadInput::RightStickRight},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                    {"Analog Stick Up", input::GamepadInput::LeftStickUp},
                    {"Analog Stick Down", input::GamepadInput::LeftStickDown},
                    {"Analog Stick Left", input::GamepadInput::LeftStickLeft},
                    {"Analog Stick Right", input::GamepadInput::LeftStickRight},
                }}},
      .settings = {
          CoreOption{.key = "mupen64plus-169screensize",
                     .defaultValue = "960x540"},
          CoreOption{.key = "mupen64plus-43screensize",
                     .defaultValue = "1280x960"},
          CoreOption{.key = "mupen64plus-BackgroundMode",
                     .defaultValue = "OnePiece"},
          CoreOption{.key = "mupen64plus-BilinearMode",
                     .defaultValue = "standard"},
          CoreOption{.key = "mupen64plus-CorrectTexrectCoords",
                     .defaultValue = "Off"},
          CoreOption{.key = "mupen64plus-CountPerOp", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-DitheringPattern",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-DitheringQuantization",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableCopyAuxToRDRAM",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableCopyColorToRDRAM",
                     .defaultValue = "Async"},
          CoreOption{.key = "mupen64plus-EnableCopyDepthToRDRAM",
                     .defaultValue = "Software"},
          CoreOption{.key = "mupen64plus-EnableEnhancedHighResStorage",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableEnhancedTextureStorage",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableFBEmulation",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-EnableFragmentDepthWrite",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-EnableHWLighting",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableHiResAltCRC",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableLODEmulation",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-EnableLegacyBlending",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableN64DepthCompare",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableNativeResFactor",
                     .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-EnableNativeResTexrects",
                     .defaultValue = "Disabled"},
          CoreOption{.key = "mupen64plus-EnableOverscan",
                     .defaultValue = "Enabled"},
          CoreOption{.key = "mupen64plus-EnableShadersStorage",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-EnableTexCoordBounds",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-EnableTextureCache",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-FXAA", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-ForceDisableExtraMem",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-FrameDuping", .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-Framerate",
                     .defaultValue = "Original"},
          CoreOption{.key = "mupen64plus-GLideN64IniBehaviour",
                     .defaultValue = "late"},
          CoreOption{.key = "mupen64plus-HybridFilter", .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-IgnoreTLBExceptions",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-MaxTxCacheSize",
                     .defaultValue = "8000"},
          CoreOption{.key = "mupen64plus-MultiSampling", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-OverscanBottom", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-OverscanLeft", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-OverscanRight", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-OverscanTop", .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-RDRAMImageDitheringMode",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-ThreadedRenderer",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-alt-map", .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-angrylion-multithread",
                     .defaultValue = "all threads"},
          CoreOption{.key = "mupen64plus-angrylion-overscan",
                     .defaultValue = "disabled"},
          CoreOption{.key = "mupen64plus-angrylion-sync",
                     .defaultValue = "Low"},
          CoreOption{.key = "mupen64plus-angrylion-vioverlay",
                     .defaultValue = "Filtered"},
          CoreOption{.key = "mupen64plus-aspect", .defaultValue = "4:3"},
          CoreOption{.key = "mupen64plus-astick-deadzone",
                     .defaultValue = "15"},
          CoreOption{.key = "mupen64plus-astick-sensitivity",
                     .defaultValue = "100"},
          CoreOption{.key = "mupen64plus-cpucore",
                     .defaultValue = "dynamic_recompiler"},
          CoreOption{.key = "mupen64plus-d-cbutton", .defaultValue = "C3"},
          CoreOption{.key = "mupen64plus-l-cbutton", .defaultValue = "C2"},
          CoreOption{.key = "mupen64plus-pak1", .defaultValue = "memory"},
          CoreOption{.key = "mupen64plus-pak2", .defaultValue = "none"},
          CoreOption{.key = "mupen64plus-pak3", .defaultValue = "none"},
          CoreOption{.key = "mupen64plus-pak4", .defaultValue = "none"},
          CoreOption{.key = "mupen64plus-parallel-rdp-deinterlace-method",
                     .defaultValue = "Bob"},
          CoreOption{.key = "mupen64plus-parallel-rdp-dither-filter",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-divot-filter",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-downscaling",
                     .defaultValue = "disable"},
          CoreOption{.key = "mupen64plus-parallel-rdp-gamma-dither",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-native-tex-rect",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-native-texture-lod",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-parallel-rdp-overscan",
                     .defaultValue = "0"},
          CoreOption{.key = "mupen64plus-parallel-rdp-super-sampled-read-back",
                     .defaultValue = "False"},
          CoreOption{
              .key = "mupen64plus-parallel-rdp-super-sampled-read-back-dither",
              .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-synchronous",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-upscaling",
                     .defaultValue = "1x"},
          CoreOption{.key = "mupen64plus-parallel-rdp-vi-aa",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-parallel-rdp-vi-bilinear",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-r-cbutton", .defaultValue = "C1"},
          CoreOption{.key = "mupen64plus-txCacheCompression",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-txEnhancementMode",
                     .defaultValue = "None"},
          CoreOption{.key = "mupen64plus-txFilterIgnoreBG",
                     .defaultValue = "True"},
          CoreOption{.key = "mupen64plus-txFilterMode", .defaultValue = "None"},
          CoreOption{.key = "mupen64plus-txHiresEnable",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-txHiresFullAlphaChannel",
                     .defaultValue = "False"},
          CoreOption{.key = "mupen64plus-u-cbutton", .defaultValue = "C4"},
          CoreOption{.key = "mupen64plus-virefresh", .defaultValue = "Auto"},
      }});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_NINTENDO_DS,
      .name = "Nintendo DS",
      .abbreviation = "NDS",
      .slug = "nds",
      .fileAssociations = {"nds"},
      .controllerTypes =
          {{.id = 1,
            .name = "Retropad",
            .imageUrl = "qrc:/images/controllers/nds",
            .inputs =
                {
                    {"A", input::GamepadInput::EastFace},
                    {"B", input::GamepadInput::SouthFace},
                    {"X", input::GamepadInput::NorthFace},
                    {"Y", input::GamepadInput::WestFace},
                    {"L", input::GamepadInput::LeftBumper},
                    {"R", input::GamepadInput::RightBumper},
                    {"Start", input::GamepadInput::Start},
                    {"Select", input::GamepadInput::Select},
                    {"D-Pad Up", input::GamepadInput::DpadUp},
                    {"D-Pad Down", input::GamepadInput::DpadDown},
                    {"D-Pad Left", input::GamepadInput::DpadLeft},
                    {"D-Pad Right", input::GamepadInput::DpadRight},
                    {"Move cursor up", input::GamepadInput::RightStickUp},
                    {"Move cursor down", input::GamepadInput::RightStickDown},
                    {"Move cursor left", input::GamepadInput::RightStickLeft},
                    {"Move cursor right", input::GamepadInput::RightStickRight},
                    {"Touch with cursor", input::GamepadInput::R3},
                    {"Enable microphone (hold)",
                     input::GamepadInput::LeftTrigger},
                    {"Change screen layout", input::GamepadInput::RightTrigger},
                    {"Close lid", input::GamepadInput::L3},
                }}},
      .settings = {CoreOption{.key = "melonds_homebrew_sdcard",
                              .defaultValue = "disabled"},
                   CoreOption{.key = "melonds_number_of_screen_layouts",
                              .defaultValue = "8"}}});

  m_platforms.emplace_back(
      Platform{.id = PLATFORM_ID_SEGA_MASTER_SYSTEM,
               .name = "Master System",
               .abbreviation = "Master System",
               .slug = "sms",
               .fileAssociations = {"sms"},
               .controllerTypes =
                   {{.id = 1,
                     .name = "Retropad",
                     .imageUrl = "qrc:/images/controllers/sms",
                     .inputs =
                         {
                             {"1", input::GamepadInput::SouthFace},
                             {"2", input::GamepadInput::EastFace},
                             {"Start", input::GamepadInput::Start},
                             {"D-Pad Up", input::GamepadInput::DpadUp},
                             {"D-Pad Down", input::GamepadInput::DpadDown},
                             {"D-Pad Left", input::GamepadInput::DpadLeft},
                             {"D-Pad Right", input::GamepadInput::DpadRight},
                         }}},
               .settings = {}});
  m_platforms.emplace_back(
      Platform{.id = PLATFORM_ID_SEGA_GENESIS,
               .name = "Genesis/Mega Drive",
               .abbreviation = "Genesis/MD",
               .slug = "gen",
               .fileAssociations = {"md", "gen"},
               .controllerTypes = {
                   {.id = 1,
                    .name = "Retropad",
                    .imageUrl = "qrc:/images/controllers/gen-threebutton",
                    .inputs = {
                        {"A", input::GamepadInput::WestFace},
                        {"B", input::GamepadInput::SouthFace},
                        {"C", input::GamepadInput::EastFace},
                        {"X", input::GamepadInput::LeftBumper},
                        {"Y", input::GamepadInput::NorthFace},
                        {"Z", input::GamepadInput::RightBumper},
                        {"Start", input::GamepadInput::Start},
                        {"Mode", input::GamepadInput::Select},
                        {"D-Pad Up", input::GamepadInput::DpadUp},
                        {"D-Pad Down", input::GamepadInput::DpadDown},
                        {"D-Pad Left", input::GamepadInput::DpadLeft},
                        {"D-Pad Right", input::GamepadInput::DpadRight},
                    }}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_SEGA_GAMEGEAR,
      .name = "Game Gear",
      .abbreviation = "Game Gear",
      .slug = "gg",
      .fileAssociations = {"gg"},
      .controllerTypes = {{.id = 1,
                           .name = "Retropad",
                           .imageUrl = "qrc:/images/controllers/gg",
                           .inputs = {
                               {"1", input::GamepadInput::SouthFace},
                               {"2", input::GamepadInput::EastFace},
                               {"Start", input::GamepadInput::Start},
                               {"D-Pad Up", input::GamepadInput::DpadUp},
                               {"D-Pad Down", input::GamepadInput::DpadDown},
                               {"D-Pad Left", input::GamepadInput::DpadLeft},
                               {"D-Pad Right", input::GamepadInput::DpadRight},
                           }}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_TURBOGRAFX16,
      .name = "PC Engine/TurboGrafx-16",
      .abbreviation = "PCE/TG-16",
      .slug = "pce",
      .fileAssociations = {"pce"},
      .controllerTypes = {
          {.id = 1,
           .name = "Retropad",
           .imageUrl = "qrc:/images/controllers/tgx-twobutton",
           .inputs = {
               {"I", input::GamepadInput::EastFace},
               {"II", input::GamepadInput::SouthFace},
               {"III (six-button mode)", input::GamepadInput::WestFace},
               {"IV (six-button mode)", input::GamepadInput::NorthFace},
               {"V (six-button mode)", input::GamepadInput::LeftBumper},
               {"VI (six-button mode)", input::GamepadInput::RightBumper},
               {"Toggle mode", input::GamepadInput::LeftTrigger},
               {"Run", input::GamepadInput::Start},
               {"Select", input::GamepadInput::Select},
               {"D-Pad Up", input::GamepadInput::DpadUp},
               {"D-Pad Down", input::GamepadInput::DpadDown},
               {"D-Pad Left", input::GamepadInput::DpadLeft},
               {"D-Pad Right", input::GamepadInput::DpadRight},
           }}}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_SUPERGRAFX,
      .name = "SuperGrafx",
      .abbreviation = "SuperGrafx",
      .slug = "sgx",
      .fileAssociations = {"sgx"},
      .controllerTypes = {
          {.id = 1,
           .name = "Retropad",
           .imageUrl = "qrc:/images/controllers/tgx-twobutton",
           .inputs = {
               {"I", input::GamepadInput::EastFace},
               {"II", input::GamepadInput::SouthFace},
               {"III (six-button mode)", input::GamepadInput::WestFace},
               {"IV (six-button mode)", input::GamepadInput::NorthFace},
               {"V (six-button mode)", input::GamepadInput::LeftBumper},
               {"VI (six-button mode)", input::GamepadInput::RightBumper},
               {"Toggle mode", input::GamepadInput::LeftTrigger},
               {"Run", input::GamepadInput::Start},
               {"Select", input::GamepadInput::Select},
               {"D-Pad Up", input::GamepadInput::DpadUp},
               {"D-Pad Down", input::GamepadInput::DpadDown},
               {"D-Pad Left", input::GamepadInput::DpadLeft},
               {"D-Pad Right", input::GamepadInput::DpadRight},
           }}}});
  m_platforms.emplace_back(
      Platform{.id = PLATFORM_ID_POKEMON_MINI,
               .name = "Pokémon Mini",
               .abbreviation = "Pokémon Mini",
               .slug = "pkmn",
               .fileAssociations = {"min"},
               .controllerTypes =
                   {{.id = 1,
                     .name = "Retropad",
                     .imageUrl = "qrc:/images/controllers/pkmn-mini",
                     .inputs =
                         {
                             {"A", input::GamepadInput::EastFace},
                             {"B", input::GamepadInput::SouthFace},
                             {"C", input::GamepadInput::RightBumper},
                             {"D-Pad Up", input::GamepadInput::DpadUp},
                             {"D-Pad Down", input::GamepadInput::DpadDown},
                             {"D-Pad Left", input::GamepadInput::DpadLeft},
                             {"D-Pad Right", input::GamepadInput::DpadRight},
                             {"Shake", input::GamepadInput::LeftBumper},
                             {"Power", input::GamepadInput::Select},
                         }}},
               .settings = {}});
  m_platforms.emplace_back(Platform{
      .id = PLATFORM_ID_WONDERSWAN,
      .name = "WonderSwan",
      .abbreviation = "WonderSwan",
      .slug = "ws",
      .fileAssociations = {"ws", "wsc"},
      .controllerTypes = {
          {.id = 1,
           .name = "Retropad",
           .imageUrl = "qrc:/images/controllers/ws-horizontal",
           .inputs = {
               {"X1 (Horizontal), Y2 (Vertical)", input::GamepadInput::DpadUp},
               {"X2 (Horizontal), Y3 (Vertical)",
                input::GamepadInput::DpadRight},
               {"X3 (Horizontal), Y4 (Vertical)",
                input::GamepadInput::DpadDown},
               {"X4 (Horizontal), Y1 (Vertical)",
                input::GamepadInput::DpadLeft},
               {"A (Horizontal), X3 (Vertical)", input::GamepadInput::EastFace},
               {"B (Horizontal), X4 (Vertical)",
                input::GamepadInput::SouthFace},
               {"X1 (Horizontal)", input::GamepadInput::WestFace},
               {"X2 (Horizontal)", input::GamepadInput::NorthFace},
               {"Start", input::GamepadInput::Start},
               {"Switch orientation", input::GamepadInput::Select},
           }}}});
}
std::optional<Platform> PlatformService::getPlatform(const unsigned id) const {
  for (const auto &platform : m_platforms) {
    if (platform.id == id) {
      return platform;
    }
  }

  return {};
}
std::vector<Platform> PlatformService::listPlatforms() const {
  return m_platforms;
}

} // namespace firelight::platforms
